# Utiliser une image de base pour Python
FROM python:3.11-slim

# Installer les dépendances nécessaires
RUN apt-get update && apt-get install -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Copier le fichier des requirements
COPY ./producer/requirements.txt .

# Installer les dépendances Python
RUN pip install --no-cache-dir -r requirements.txt

# Copier le script Python
COPY ./producer/ /app
WORKDIR /app
